spring.application.name=Lofau



spring.datasource.url=jdbc:postgresql://localhost:5433/lofau
spring.datasource.username=postgres
spring.datasource.password=2024

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



application.security.jwt.secret-key=9b8e5e3f1d6c4a8b7f2a1c3d5e6f8a9b9b8e5e3f1d6c4a8b7f2a1c3d5e6f8a9b
application.security.jwt.expiration=86400000

cloudinary.cloud-name=droomnbwy
cloudinary.api-key=912627424551665
cloudinary.api-secret=AKwmRXfjXDLPGqDAgwqNFz02lgs